### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by jkpang** [joeblau/sensor-visualizer-kit#1]
![image](https://user-images.githubusercontent.com/17583451/56659712-6f6a9f00-66d0-11e9-872e-5af52af354ee.png)

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by inickt** [comment]
Looks like you don't have `git-lfs` installed. See https://git-lfs.github.com/

**Comment by jkpang** [comment]
> Looks like you don't have `git-lfs` installed. See https://git-lfs.github.com/

Thanks！
